[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition      = "2024"
rust-version = "1.97"
license      = "Apache-2.0"
repository   = "https://github.com/thegenem0/hadar"

[workspace.dependencies]
storage-api = { version = "0.1.0", path = "crates/storage-api" }
thiserror = { version = "2", default-features = false, features = ["std"] }
# tracing   = { version = "0.1", default-features = false, features = ["std", "attributes"] }

[workspace.lints.rust]
missing_docs                  = "warn"
missing_debug_implementations = "warn"
redundant_lifetimes           = "warn"
trivial_numeric_casts         = "warn"
unused_lifetimes              = "warn"
unused_qualifications         = "warn"
unsafe_code                   = "deny"
unsafe_op_in_unsafe_fn        = "deny"
rust_2018_idioms              = { level = "warn", priority = -1 }

[workspace.lints.clippy]
pedantic                       = { level = "warn", priority = -1 }
allow_attributes               = "warn"
allow_attributes_without_reason = "warn"
clone_on_ref_ptr               = "warn"
undocumented_unsafe_blocks     = "warn"
unused_result_ok               = "warn"
unwrap_used                    = "warn"
expect_used                    = "warn"
