[package]
name = "api"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mvcc = { workspace = true }
prost = { workspace = true }
storage-api = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
protox = { workspace = true }
tonic-prost-build = { workspace = true }

[lints]
workspace = true
